name: Restrict Pushes Outside Workbench

on:
  push:
    branches:
      - main  # Or your protected branch

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check modified files
        run: |
          echo "Checking for changes outside Workbench/"
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files: $CHANGED_FILES"

          # Look for any file outside Workbench/
          if echo "$CHANGED_FILES" | grep -v '^Workbench/' | grep -v '^\.github/'; then
            echo "❌ Push contains changes outside Workbench/"
            exit 1
          fi
